language: ruby
rvm:
  - 2.6

# branch whitelist, only for Github pages
# https://jekyllrb.com/docs/continuous-integration/travis-ci/
branches:
  only:
  - master

env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true # speed up html-proofer install

sudo: false # route build to the container-based infrastructure for faster build
