--- 
about: true
animation: true
authors: 
  emi: 
    bio: "Software developer and keyboard lover"
    external-image: false
    name: "Emiliano Montesdeoca"
    picture: assets/images/james.jpg
    twitter: emimontesdeocaa
bio: "Software developer and keyboard lover"
blog: true
description: "A blog about software and stuff related"
disqus: 
  categories: 
    - blog
    - project
  shortname: https-emimontesdeoca-github-io
email: emontesdeoc@gmail.com
external-image: false
facebook: emimontesdeocadelpuerto
github: emimontesdeoca
instagram: emimontesdeoca
jekyll-mentions: 
  base_url: "https://github.com"
linkedin: emimontesdeoca
name: "Emiliano Montesdeoca"
permalink: "/:title/"
picture: assets/images/profile.jpg
plugins: 
  - jekyll-seo-tag
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-admin
post-advance-links: 
  - blog
projects: true
read-time: true
reddit: emontesdeoca
related: true
resume: true
resume-external: true
resume-url: "https://drive.google.com/open?id=1idOWXUlALiJ6VXLn-pBlxboxDwjZFGv-"
show-author: true
show-tags: true
stackoverflow: 7823470/emiliano-montesdeoca
twitter: emimontesdeocaa
url: "https://emimontesdeoca.github.io"
width: large
